'use client';

import Header from '@/components/Header';
import '@/app/globals.css';
import { Poppins } from 'next/font/google';
import { UserStorage } from '@/context/UserContext';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-popins',
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserStorage>
          <Header />
          {children}
        </UserStorage>
      </body>
    </html>
  );
}
