import Feed from '@/components/Feed/Feed';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <section className="">
      <Feed />
    </section>
  );
}
